---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: "{{ template "fullname" . }}-daemonset"
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      component: "{{ template "fullname" . }}-daemonset"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ template "fullname" . }}-daemonset"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: "{{ .Values.fluentd.image.repository }}:{{ default .Chart.AppVersion .Values.fluentd.image.tag }}"
        imagePullPolicy: {{ .Values.fluentd.image.pullPolicy | quote }}
        env:
          - name: OS_MONASCA_LOG_API_URL
            value: {{ .Values.monasca_log_url | quote }}
          - name: OS_KEYSTONE_URL
            value: {{ .Values.keystone.url | quote }}
          - name: OS_USERNAME
            value: {{ .Values.keystone.os_username | quote }}
          - name: OS_PASSWORD
            value: {{ .Values.keystone.os_password | quote }}
          - name: OS_DOMAIN_ID
            value: {{ .Values.keystone.os_domain_id | quote }}
          - name: OS_PROJECT_NAME
            value: {{ .Values.keystone.os_project_name | quote }}
          - name: LOG_LEVEL
            value: {{ lower .Values.log_level | quote }}
          - name: FLUENT_UID
            value: "0"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
